### ISSUE TITLE
Support for CUDA 10.1 version?

### ISSUE THREAD

**Issue by psurya1994** [deepmind/acme#127]
When I install the environment using instructions in `README.md`, libraries are setup to use CUDA11. But I setup CUDA10.1 on my system, so things don't work off the bat. Is there an easy way to get acme to work with CUDA10.1? I've spent a couple of hours trying different things with little success.

**Comment by mwhoffman** [comment]
Hi! Unfortunately I think the answer to this is no and you'll have to upgrade CUDA.

To provide some more context: technically acme doesn't really care what version of CUDA you have. _HOWEVER_ we rely on tensorflow (or jax in some situations, but it sounds like you're using tensorflow) for GPU support. If you were able to install tensorflow in a way that works with CUDA 10.1 that might work. Unfortunately, I think the current versions of tensorflow only support CUDA 11, and because of our reliance of reverb (and some other compiled components) there's a somewhat tight window around the versions of TF that work with acme.

As a result, I think you'll have to upgrade CUDA. While I don't want to entirely rule out the possibility that this could be made to work... I do think it's unlikely and even if so it will be harder than upgrading CUDA and not something that we'd be able to help with.

If you're not already running under a docker image (see https://www.tensorflow.org/install/docker) that might also help. This is what I'd usually recommend as a way to avoid any version mismatches with your system. Unfortunately though this will likely require the CUDA driver to be updated---but that's it!

**Comment by psurya1994** [comment]
This is great information, thank you @mwhoffman! Helps me think much more clearly.
