### ISSUE TITLE
How to configure your own environment

### ISSUE THREAD

**Issue by monkeycc** [deepmind/acme#167]
simulator： VirtuaNES
game： Super Mario Bros
WIN10-11

```
# VirtuaNES 
# https://www.emulator-zone.com/doc.php/nes/virtuanes.html

# Super Mario Bros ROM
# https://wowroms.com/en/roms/nintendo-entertainment-system/download-super-mario-bros./23755.html
```

Like playing Super Mario Bros with virtuanes

Tutorial required

Learning by demonstration

ACME How to configure the environment

<img width="365" alt="1111111111111111" src="https://user-images.githubusercontent.com/6490927/141608099-7f7b2902-2c11-42f9-ac2c-fd5aa702c9d4.png">

**Comment by nikolamomchev** [comment]
@monkeycc I don't fully understand what are you asking for from the description. Could you please elaborate?

**Comment by monkeycc** [comment]
For example, NES games, PC games, Android games

How do I configure the environment interface and interface with acme

Do not use gym environment

In their own games, their own game interface, reinforcement learning and simulation learning

**Comment by nikolamomchev** [comment]
Got it. Acme assumes your environment implements the dm_env interface. In order to try different games you'll have to implement a Python object which exposes the interface and interacts with the game. The best way to do that will depend on the game itself and what is your goal (e.g. do you have access to the interval state of the have or just pixels etc.).

This is, however, our of the scope of Acme so I'll close this issue.
