### ISSUE TITLE
How to use mixed type inputs

### ISSUE THREAD

**Issue by peterdec** [deepmind/acme#173]
Hi, I have a question regarding mixed inputs, such as image + some other data. I would like to feed the image through some convolutional layers and feed the output of that along with the other inputs into the following dense layers of the agent network. But I am not quite sure how that would be accomplished with Acme, since the observations are handed to the agent as one and I have no control over how they are used internally. 

Therefore, I would be interested in seeing an example where these types of inputs are combined. For instance, if you expose the lives in atari as an additional observation. The wrapper allows for that, but your run_dqn example doesn’t seem to make use of it. So how would one avoid that the life observation is used as input for the atari torso?

Any help would be much appreciated.

**Comment by bshahr** [comment]
Hi peterdec,

Thanks for the great question! Indeed we've been meaning to add an example with mixed inputs for some time but haven't got around to it. However in some cases the solution to this can be quite simple. Assuming you're fine with having separate pipelines (torsos) for each input type and combine them somehow before the rest of your network, you can implement all of this as a torso defined in your custom network factory.

For instance, in your stated example, you could have a torso that is aware of the nested structure of the input (perhaps a dictionary with 'image' and 'life_lost' values); you can then run the image through a conv stack (e.g. `hk.Resnet()(inputs['image'])`) and the 'life_lost' bit through something else (e.g. `hk.Embed()(inputs['life_lost'])`), combining the two somehow for an output (e.g. concatenate).

Note that I'm not suggesting those transforms or combination operation are a good choice, I've simply picked them to illustrate the approach. Hope this answers your question! Feel free to reopen with a follow-up otherwise :)
