### ISSUE TITLE
Why different replay table setup for R2D2 in Jax vs. TF agent?

### ISSUE THREAD

**Issue by wcarvalho** [deepmind/acme#180]
Specifically why does the JAX version have 2 options while the TF version has 1 option. I assume there's some benefit?

JAX: https://github.com/deepmind/acme/blob/dbd70073fffedef86bb933e88d5e675a2630f3e2/acme/agents/jax/r2d2/builder.py#L111

TF: https://github.com/deepmind/acme/blob/dbd70073fffedef86bb933e88d5e675a2630f3e2/acme/agents/tf/r2d2/agent.py#L84

**Comment by nikolamomchev** [comment]
@wcarvalho our development was mostly focused on JAX for quite some time now and the TF agents may have fallen behind. If in doubt, I'd always suggest referring to the JAX implementations.

The two options in the jax version are there in order to support running R2D2 in both local and distributed setups. In case you want to run DistributedR2D2, you'd probably want to use the reverb rate limiter and tweak `samples_per_insert`. In the single-process synchronous version you don't need the rate limiter. In fact it can deadlock if you enable it, so you'd better set `samples_per_insert` to `0`.

I hope this was clear enough. Feel free to reopen if it was not.

**Comment by wcarvalho** [comment]
Thank you! This was helpful.
