### ISSUE TITLE
Why Acme is using own uniform initializer?

### ISSUE THREAD

**Issue by markub3327** [deepmind/acme#187]
Why is Acme using own initializer for both tanh and ELU, when commonly used for tanh is Xavier and for ELU is He initializer? What mathematics is behind them?

The code: https://github.com/deepmind/acme/blob/master/acme/tf/networks/continuous.py
  
```python
uniform_initializer = tf.initializers.VarianceScaling(
    distribution='uniform', mode='fan_out', scale=0.333)
```

Thanks.

**Comment by nikolamomchev** [comment]
@markub3327 I tried to dig out the answer for this, but unfortunately I couldn't find anyone knowledgeable within the time budget I had set for this. I am not sure if this makes any difference or if it was intentional.

If you have evidence that using a different initialiser works better, please point us at it - we'd be happy to revise this.
