### ISSUE TITLE
Does the DistributedD4PG agent automatically utilizes multiple GPUs?

### ISSUE THREAD

**Issue by templarares** [deepmind/acme#188]
Hi acme team,

I am trying to speed up the training of my DistributedD4PG agent. I am wondering if a multi-CPU configuration would do the trick without changing the current code? Thanks!

**Comment by nikolamomchev** [comment]
Hi @templarares ,

The D4PG learner currently does not support pmapping, which means that it would only run on a single accelerator. In our experiments we use TPUs and so far this was enough for us. Note that in many cases the bottleneck was not the learner itself but rather collecting and sending the experience to the learner.

One thing you could try to squeeze more performance is to increase the num_sgd_steps_per_step parameter (https://github.com/deepmind/acme/blob/67ee5c80dfdc1e5ac1f973163e4d96928d52b567/acme/agents/jax/d4pg/builder.py#L65). This introduced a non-trivial speedup in our experiments.

**Comment by templarares** [comment]
Hi @nikolamomchev ,

Thanks for your quick response! But I just realized that I have made a typo in my question statement... By "multi-CPU configuration" I was actually trying to say "multi-GPU"... So, if I add an extra GPU to my current mono-GPU host, can I expect to be able to create more actors under DistributedD4PG so as to generate experiences faster? Thanks again!

**Comment by nikolamomchev** [comment]
Ah, I thought you are asking about using multi-GPU setup for speeding up the _learner_. The trick I mentioned above will help with the learner, not with experience collection.

Actors currently are setup to run NN inference on CPU. Changing the backend [here](https://github.com/deepmind/acme/blob/67ee5c80dfdc1e5ac1f973163e4d96928d52b567/acme/agents/jax/d4pg/builder.py#L201) _should_ be enough to make use of multiple GPUs for inference during experience collection. Note, however, that in many cases the bottleneck for experience collection is in running the environments (which are more often CPU-bound than GPU-bound). In such cases running the networks on GPU won't help. We would usually run multiple actors on different machines in order to address this. Running several actors in different processes on the same machine might also help if the machine is powerful enough to efficiently run multiple instances of the environment.

I hope this sufficiently answers your question. I'll close the issue for now, but feel free to reopen if you have further questions.

**Comment by templarares** [comment]
Hi @nikolamomchev ,

Thanks for your response. But I cannot reopen this issue, as it was not closed by myself...

**Comment by nikolamomchev** [comment]
From @templarares posted on #190
> Hi nikolamomchev, Please excuse me for keep asking about this: You explained that actors are running NN on CPU, but they are using the GPU somewhere else, right? As each of my actor processes, created by Distributed D4PG via LaunchPad, consumes about 580MB of my RTX 2080's memory (after turning on the "memory_growth" option for my GPU in TF). So I can only run 10 actors in the same time on my host, as together with the learner and evaluator they will take most of my GPU's 8GB memory. In the same time my CPU usage is only 66% and memory usage below 50%. So I identified the performance bottleneck in my situation as the GPU. Thus I was wondering if simply adding another 2080 will help, without too much modification of the code, of course. Thanks again for your patience and responses!

If your actors are consuming GPU resources, then adding more GPUs should work out of the box. Actors are running as independent processes and they don't need to communicate to each other - you can even run them on different machines. Note that in this case it's most likely that your environment consumes the GPU as NN inference happens on the CPU.

Please close the issue if you feel this sufficiently answers your question.

**Comment by templarares** [comment]
> 

I get it now. D4PG itself does not consume GPU resource. Thank you very much for your clarification!

**Comment by nikolamomchev** [comment]
Just to clarify - the actors won't use GPU for neural network inference. The learner will still use an accelerator for neural network training if one is available.
