### ISSUE TITLE
Gym Environment ( no available MuJoCo access ) 

### ISSUE THREAD

**Issue by mosicr** [deepmind/acme#21]
Hi, 
Is it possible to release Gym-only based  tutorial version ? It'd be helpful for people with no MuJoCo licence. 

Regards, Ranko.

**Comment by bshahr** [comment]
Hi mosicr,
We've had a few requests for this now and are currently working on a working example to add to the repo. Stay tuned!

**Comment by mosicr** [comment]
Great, while you are at it .. it should also work in Colab, otherwise the whole stuff is useless.

**Comment by HuzzDTX** [comment]
Hi mosicr, 
The gym_mountaincar environment in the tutorial works fine without MuJoCo licence, I managed to run it in Colab without issue. I also tried to run the link you provided "as a guideline" and its crashing :)

Regards
Hazem

**Comment by mosicr** [comment]
Hi Hazem,
The link is working, just tested it,  you gotta restart session after cell #1 runs, as instructed in the output. Now it seems like Google geniuses managed to break the rest of tf.agent tutorials ( DQN etc ) that were previously working. 
Pray tell exactly what you run ( provide colab link etc ).

**Comment by HuzzDTX** [comment]
Use the Colab link in https://github.com/deepmind/acme/blob/master/examples/tutorial.ipynb.
you need to make the following edits to run the gym_mountaincar :

1- in cell 2 "dm_control", comment out or delete the cell.
2- in cell 3 "Import Modules", replace %%capture with the following "this was copied from cell 2" 
from IPython.display import clear_output
clear_output()
3- in the load environment section make sure you select gym_mountaincar from the drop down.

Run each cell to finish and it will show you a small video at the end of the trained agent.

This should allow you to run the tutorial with no error but with some warnings, but the final result is not great out of the box, you need to make some tweaks to make it learn a better policy, I will leave that to you because I don't want to ruin the fun,

Thanks Deep mind for the great package, having this as an open source is a great asset for the community, 

Regards
Hazem

**Comment by mosicr** [comment]
Great, thanks Hazem it works !!

**Comment by bshahr** [comment]
Hi you two, good news here!

First off, thanks @HuzzDTX for stepping in with some very helpful tech support! Truly appreciated :)

We've cleaned up the Quickstart guide so that hopefully it's more clear and also works out of the box. Both gym and dm_control examples should work with the agent as it is defined in the colab but feel free to play around with those settings and see how it affects learning!

Thanks for reporting these issues. Enjoy!
