### ISSUE TITLE
Jitted Jax Environment Loop Support

### ISSUE THREAD

**Issue by djbyrne** [deepmind/acme#220]
Hi,
I was just wondering if there were any future plans for ACME to support fully jittable jax environment loops? It would be really cool to be able to jit the enitre training loop, assuming that you are using jax based environments like Brax. Do you think this would be on ACME's roadmap?

Thanks,

Donal

**Comment by nikolamomchev** [comment]
Thanks for the question @djbyrne. We have given this a lot of thought internally and the answer is kind of complex. A TL;DR; would be "No, but...".

Let me elaborate:

No:
I don't think we'll ever be able to have the full *training loop* jittable in Acme. We tried hard to do this and figured it's not rally feasible if we want to keep the flexibility we currently have in the framework.

But:
1) As you may know Brax has several training algorithms implemented. We are actually working closely with the brax team to make those more flexible and set them up so that they can be executed on any fully-jitted environment. We are also looking for potential opportunities to allow for reusing as much as possible of Acme's algorithm implementations in Brax. This is however further down the roadmap.
2) A lot of the performance benefit of jitted environments comes from the fact that they can run in batched mode. @qstanczyk is actually actively working on a change which will allow us to run such environments in batch mode and hopefully gain significant performance improvements from this. This can be paired with running the policy networks in batch mode (support for this was added in https://github.com/deepmind/acme/commit/a917c9d20a59044921fd709198c6c73bb7e20f77). In fact, I believe @qstanczyk will soon submit a Brax example which employs this setup. This probably won't be as efficient as what you can get from a fully accelerated training, but we hope it strikes a good balance between performance and flexibility.

**Comment by cemlyn007** [comment]
FYI for anyone interested, the policy networks in batch mode support has been [removed](https://github.com/deepmind/acme/commit/51f6346ecb7e7f69f5b977f0e79e01e5155ca462).
