### ISSUE TITLE
Rendering atari environment

### ISSUE THREAD

**Issue by dcharrezt** [deepmind/acme#26]
Hi, thanks for open sourcing this framework

I was trying to visualize what the agent has learned, but I could not render the atari environment.

After the `GymAtariAdapter` wrapper is used when I try to render the environment I get

```bash
AttributeError: 'AtariWrapper' object has no attribute 'render'
```

And I can not unwrap it either

```bash
'AtariWrapper' object has no attribute 'unwrapped'
```

I apologize if this is the intended behavior.

**Comment by bshahr** [comment]
Hi dcharrezt,
Thanks for pointing this out! It seems we don't have a public pointer to the unwrapped environment. For now you can use `AtariWrapper._environment`, we'll try to fix this soon.

**Comment by bshahr** [comment]
This actually may be as simple as making `AtariWrapper` inherit from `acme.wrappers.base.EnvironmentWrapper`, then you'll have access to the unwrapped environment via the unprotected `EnvironmentWrapper.environment` instead. Can anyone confirm that this doesn't have any unwanted side effects? Otherwise I'll try to look into this next week.

**Comment by TheSnowGuru** [comment]
Hey guys, I created a discord for this project to be able to better contribute to the issues,share training results and more,  enjoy. 
https://discord.gg/Rf6EU7

**Comment by aslanides** [comment]
This should be resolved now. Let me know if you have any other issues.
