### ISSUE TITLE
dm_contol env.seed, reward/action normalization, and acme.wrapper

### ISSUE THREAD

**Issue by rasoolfa** [deepmind/acme#60]
Hi,

I have a couple of questions about **dm_contol** and differences with **gym**, can you please advice?

1. Reward for any task in **dm_contol** is bounded in (-1,1) per acme authors' comments.  Can acme_wrapper also be used to create a gym env where reward for any task is bounded in (-1,1)? the following doesn't seem to bound rewards.

```
from acme import wrappers
env_gym = gym.make('Hopper-v3')
env_dc = wrappers.GymWrapper(env_gym)
env_dc = wrappers.SinglePrecisionWrapper(env_dc)
```
2. Should _actions_ be scaled into a specific range say [-1, 1] in a continuous environments in order to work with **dm_control**?

3. In gym, one can simply use the followings to set up [environment] random seeds to make results reproducible:

```
    env.seed(seed)
    env.action_space.np_random.seed(seed)
```
It seems  **dm_contol** doesn't have this functionality. Can you help how that can be done?

4. Does env.step(action) act differently than gym's step()? For one they return [almost] different things in a different order, but are there other differences?

**gym:**
```
observation, reward, done, info =  env.step(action)
```
**dm_control:**
```
step_type, reward, discount, observation =  env.step(action)
```
5. Does using **acme.wrappers** make gym to be more like **dm_contol** ? or it changes its functionalities like step function? in general when one should use  **acme.wrappers** [for gym]?

Thanks for your help.

**Comment by ethanluoyc** [comment]
Hi @rasoolfa,

I'd like to share some experience with how I dealt with integration with dm_control and hopefully they will be useful to you.

> 1. Reward for any task in dm_contol is bounded in (-1,1) per acme authors' comments. Can acme_wrapper also be used to create a gym env where reward for any task is bounded in (-1,1)? the following doesn't seem to bound rewards.

You can probably achieve this by implementing your own wrappers. See 2. for how this is achieved for the action spaces. However, this probably requires you to know the limits of your reward so that you can perform the scaling.

> 2. Should actions be scaled into a specific range say [-1, 1] in a continuous environments in order to work with dm_control?

This is probably not implemented by the agents by default, but you can use the [CanonicalSpecWrapper](https://github.com/deepmind/acme/blob/master/acme/wrappers/canonical_spec.py#L34) to enforce wrapping the action ranges.

> 3. In gym, one can simply use the followings to set up [environment] random seeds to make results reproducible:

I think this functionality is available in dm_control if you pass to suite.load the relevant [task_kwargs](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/__init__.py#L93). For the tasks, they allow you to specify a random as part of the function, which can be used to fix the seeds. 

> 4. Does env.step(action) act differently than gym's step()? For one they return [almost] different things in a different order, but are there other differences?

dm_control implements the [dm_env.Environment](https://github.com/deepmind/dm_env/blob/master/dm_env/_environment.py#L85) interface, `env.step(action)` thus return a [TimeStep](https://github.com/deepmind/dm_env/blob/master/dm_env/_environment.py#L25) object (which is a named tuple, that's why you can unpack it like you did)
