### ISSUE TITLE
AZLearner: TD vs MSE-to-outcome

### ISSUE THREAD

**Issue by seb314** [deepmind/acme#7]
The [AZLearner](https://github.com/deepmind/acme/blob/4737fa56c9454a9d1b44a1778aee4e7d73c1c6c2/acme/agents/mcts/learning.py#L65-L70)  implementation here appears to do TD on transitions. 

As far as I can tell from page 2 of [the AlphaZero paper](https://science.sciencemag.org/content/362/6419/1140/tab-pdf), the original AlphaZero optimizes MSE between value-predictions and game-outcomes.

Is this an intentional variation? (Or am I misunderstanding either of the files?)

(Sorry in case this is the wrong place to put this)

**Comment by aslanides** [comment]
Hi, thanks for the question!

Yes, this (and some other details) are variations from the AlphaZero paper -- this is not intended to be a reproduction of that algorithm, but more of a general model-based RL learner, which borrows the main innovation of AZ, which is to integrate model-based planning with learned policy/value.

To answer your question, TD learning is the more general approach of the two; if there is no discounting and the reward signal is +/- 1 at game end and zero otherwise, this boils down to the MSE-to-outcome used in the AZ paper. Using TD allows us to handle environments with rewards on non-terminal transitions, such as e.g. bsuite.

Hope that helps!

**Comment by seb314** [comment]
Thanks!

One more clarification question:
Are there specific reasons that favor this approach over just replacing the binary outcome in AlphaZero's loss by the sum of discounted future rewards? (This should achieve the same generalizations, right?) 
I'd think the latter might be less susceptible to instabilities in the learned value function, but maybe other effects are more relevant in practice, or it just doesn't matter very much?

**Comment by aslanides** [comment]
What you're describing is using the complete Monte Carlo return (e.g. as used in REINFORCE) as the target rather than bootstrapping from the value function. This is known to have higher variance and is generally eschewed for boostrapping. There is however TD(lambda) which essentially allows us to mix between the two. See Ch 5-7 of Sutton & Barto: http://incompleteideas.net/book/RLbook2020.pdf
