### ISSUE TITLE
D4PG actor behavior network's Gaussian noise exploration clipped to -1 and 1

### ISSUE THREAD

**Issue by colingwuyu** [deepmind/acme#82]
https://github.com/deepmind/acme/blob/5c4b17b6e4f44f24bf92d99df050b12961f0610e/acme/agents/tf/d4pg/agent.py#L137

D4PG agent's actor behavior_network adds a ClippedGaussian which restricts action boundary within [-1, 1]. ClipToSpec(act_spec) layer after the noise will only be effective if environment's act_spec boundary is smaller than [-1, 1]. 
For an environment whose action space is larger than [-1, 1], will this behavior_network have problem in casting states into correct action space?

**Comment by bshahr** [comment]
Hi colingwuyu,

It sounds like in your case what you need is our `acme.wrappers.CanonicalSpecWrapper` Environment wrapper. This will make your environment look like it takes actions in [-1, 1] from the agent's perspective. This is nice because it reduces the number of hyperparameters you will need to change when faced with a new environment. Let us know if this doesn't solve your problem, happy to investigate your use-case further.

Bobak

**Comment by colingwuyu** [comment]
Bobak, 
Thank you very much. The wrapper definitely works it out. Thank you again for this great framework.
Colin
