### ISSUE TITLE
dm-acme[reverb] installation fails

### ISSUE THREAD

**Issue by IharBury** [deepmind/acme#9]
ERROR: Could not find a version that satisfies the requirement dm-reverb-nightly==0.1.0.dev20200529; extra == "reverb" (from dm-acme[reverb]) (from versions: 0.1.0.dev20200605)
ERROR: No matching distribution found for dm-reverb-nightly==0.1.0.dev20200529; extra == "reverb" (from dm-acme[reverb])

**Comment by IharBury** [comment]
OS: Ubuntu 20.04 LTS

**Comment by aslanides** [comment]
Just checking -- are you running under Python 3.8? 

We currently only support Python 3.6 and 3.7, but will work on getting 3.8 support in very soon (probably early next week)

**Comment by tadashiK** [comment]
A similar thing happened to me. In my case, I use Python 3.6.9 together with pipenv, and pipenv was complaining that it can't find a package satisfying 'tb-nightly<2.4.0a0,>=2.3.0a2'.

This seems to be caused by pipenv: it does not accept pre-release packages, and all tb-nightly versions were specified as 'pre-release'. I checked dm-reverb-nightly's pypi and found that all versions were specified as 'pre-release' too. So if you are using pipenv, passing `--pre` option as in `pipenv install --pre acme[reverb] ` might resolve the issue.

**Comment by IharBury** [comment]
@aslanides, you're right, dm-reverb-nightly==0.1.0.dev20200529 is not marked as Python 3.8 compatible (although the latest dm-reverb-nightly==0.1.0.dev20200605 is).
