### ISSUE TITLE
ModuleNotFoundError: No module named 'acme.environment_loops'

### ISSUE THREAD

**Issue by DriesSmit** [deepmind/acme#95]
Hello,

I am getting an error message when trying to run the open_spiel dqn.py example. I first created a virtual environment as instructed: 

`python3 -m venv acme;
source acme/bin/activate;
pip install --upgrade pip setuptools;
pip install dm-acme dm-acme[reverb] dm-acme[tf] dm-acme[jax] dm-acme[envs]`

I have python 3.8.3. Now when I run the virtual environment on the open_spiel run_dqn.py example, I get the following error message:

`ModuleNotFoundError: No module named 'acme.environment_loops'`

Does anyone know how I might fix this problem?

Thank you

**Comment by fastturtle** [comment]
Hi @DriesSmit, Looking at the command you've pasted it looks like you haven't installed open_spiel (instructions [here](https://github.com/deepmind/open_spiel/blob/master/docs/install.md#installation)).

@jhtschultz may be able to help further :)

**Comment by mwhoffman** [comment]
That would happen if you haven't installed open_spiel as @fastturtle notes, but you might also need a more cutting edge version of Acme.

We're about to push out a new release. But right now those modules are only in the version on github but not yet pushed to pypi. So e.g. something like `pip install git+git://github.com/deepmind/acme.git` should work (note that this particular command is from memory, but basically you would want to install directly from github). And we'll try and get the new version out shortly!

**Comment by DriesSmit** [comment]
Thank you @fastturtle and @mwhoffman for the feedback:) I will try your recommendations and get back to you.

**Comment by DriesSmit** [comment]
I have now tried the following (Ubuntu 20.10, python 3.8.3):

> python3 -m venv acme
> source acme/bin/activate
> pip install --upgrade pip setuptools
> pip install git+git://github.com/deepmind/acme.git
> pip3 install open_spiel
> 
> pip install gym
> pip install dm-reverb[tensorflow]
> pip install dm-sonnet
> 
> ### Open spiel specifications
> pip install tensorflow==2.2.1
> pip install absl-py==0.9.0

The command I run inside this environment:
`python3 run_dqn.py` (open_spiel example)

Open spiel seems to require TensorFlow 2.2.1. However now Reverb outputs an error as it requires TensorFlow  >= 2.3.0. So I am not exactly sure how to solve this issue. Should I maybe wait for the new Acme version?

Thank you

**Comment by jhtschultz** [comment]
Hi @DriesSmit, glad to see there's interest in using Acme with OpenSpiel :)

It looks like you are installing OpenSpiel within the same virtual environment as Acme. My approach has been to install OpenSpiel and Acme separately. After verifying they both run independently, I add the following lines (borrowed from the OpenSpiel installation instructions) to Acme's virtual environment file `./acme/bin/activate`:
```
# For the python modules in open_spiel.
export PYTHONPATH=$PYTHONPATH:/<path_to_open_spiel>
# For the Python bindings of Pyspiel
export PYTHONPATH=$PYTHONPATH:/<path_to_open_spiel>/build/python
```
Then activate only the Acme virtual environment, and try running `run_dqn.py`. Let me know if that works for you, happy to help get this up and running.

**Comment by fastturtle** [comment]
@jhtschultz would this be made easier if OpenSpiel and Reverb used the same TF version?

**Comment by jhtschultz** [comment]
For maintenance purposes it would seem preferable to minimize the amount of synchronization required between Acme and OpenSpiel. And I haven't encountered a reason why the TF versions should have to be synched. The wrapper only wraps the OpenSpiel rl_environment, which doesn’t have any dependency on TF.

**Comment by fastturtle** [comment]
Does just upgrading TF >= 2.3.0 work instead of doing the two venv approach?

@jhtschultz the issue is that Reverb makes use of some of the TF C API and if the versions (the version that was used to compile Reverb and the one installed on the user's machine) are out of sync, then there can be issues with symbol lookups. This doesn't _always_ happen, but unfortunately we've run into it before. This is the reason that we have synchronized the release schedules for Reverb, Acme, and [TF-Agents](https://github.com/tensorflow/agents). That said, it is certainly valid to continue as-is and see if the issue ever arises.

**Comment by jhtschultz** [comment]
@fastuttle ah that's good to know and I'll keep it in mind, thanks.

> Does just upgrading TF >= 2.3.0 work instead of doing the two venv approach?

I tried the single venv installation, first pip installing OpenSpiel and then Acme. Running `examples/open_spiel/run_dqn.py` successfully imports OpenSpiel (no ModuleNotFoundError), but throws `AttributeError: 'Environment' object has no attribute 'use_observation'`. This is happening because pip doesn't install the most recent version of OpenSpiel, and we modified OpenSpiel's `rl_environment.Environment` to expose `use_observation` as an attribute, rather than access the private variable `._use_observation`.

This means that currently it may be necessary to build OpenSpiel from source in order for Acme's wrapper to work.

**Comment by DriesSmit** [comment]
Thank you for the replies. I would just like to confirm the steps with you before I start:

1.) First build OpenSpiel from source using a virtual environment (https://github.com/deepmind/open_spiel/blob/master/docs/install.md). 
2.) Then build Acme in a second new virtual environment without OpenSpiel (https://github.com/deepmind/acme).
3.) In Acme environment:
```
# For the python modules in open_spiel.
export PYTHONPATH=$PYTHONPATH:/<path_to_open_spiel>
# For the Python bindings of Pyspiel
export PYTHONPATH=$PYTHONPATH:/<path_to_open_spiel>/build/python
```
4.) Run the `run_dqn.py` example.

**Comment by DriesSmit** [comment]
I got it working thanks!:) Apparently just appending 
```
# For the python modules in open_spiel.
export PYTHONPATH=$PYTHONPATH:/<path_to_open_spiel>
# For the Python bindings of Pyspiel
export PYTHONPATH=$PYTHONPATH:/<path_to_open_spiel>/build/python
```
to `./acme_env/bin/activate` not register the paths. So I just added the paths while inside the environment. Thanks for the help @mwhoffman, @fastturtle  and @jhtschultz . I appreciate it:)

**Comment by jhtschultz** [comment]
Did you reactivate the environment after adding those lines? That's the only reason I can think of offhand for why that wouldn't have worked.

Either way, I'm very glad to hear you got it working! Cheers :)
