### ISSUE TITLE
Training a single agent with multiple GPUs

### ISSUE THREAD

**Issue by ineuron** [deepmind/acme#97]
I am looking into options for speeding up learning of a R2D2 single agent and was wondering if it would be relatively straightforward to distribute the computations across multiple GPUs? Any pointers in the right direction would be greatly appreciated (or alternative suggestions for decreasing learning time). Thank you.

**Comment by nikolamomchev** [comment]
The best way to decrease learning time would depend on what's the bottleneck in your system. In most cases the bottleneck is collecting experience and for this I'd recommend running multiple actors (i.e. try out DistributedR2D2).

If the bottleneck is on the learner, it should be fairly easy to use both of your GPUs as R2D2 is already [pmap](https://jax.readthedocs.io/en/latest/_autosummary/jax.pmap.html#jax.pmap)-ing the computation in the learner. I believe all you need to do is to make sure jax has access to both accelerators.

As this issue is quite stale, I will be closing it now. If the question still stands, please submit another request and we'll try to answer to the best of our abilities.
